# SLSA Go builder config - linux/amd64
version: 1
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
flags:
  - -trimpath
  - -tags=netgo
goos: linux
goarch: amd64
binary: snippets-linux-amd64
ldflags:
  - -s -w -X main.Version={{ .Env.GO_VERSION }} -X main.BuildDate={{ .Env.GO_BUILD_DATE }}
